# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
use_frameworks!

pod 'pop', '~> 1.0'
pod 'AFNetworking', '~> 2.0'
pod 'SwiftyUserDefaults'
pod '1PasswordExtension', '~> 1.0.0'
pod 'Locksmith'
